sudo: false
language: ruby
cache: bundler

rvm:
  - 2.0
  - 2.1
  - 2.2.2
  - 2.3.1

gemfile:
 - Gemfile

branches:
  only:
      - develop
      - master

os: linux

dist: xenial

before_install: gem install bundler -v 1.13

script: bundle exec rake test

